#ifndef KAAPIF_DFG_SWITCH_H_INCLUDED
#define KAAPIF_DFG_SWITCH_H_INCLUDED
#define KAAPIF_MAX_ARGS 32
#define KAAPIF_DFG_SWITCH(__ti) \
switch((__ti)->nargs)\
{\
case 0: (__ti)->body(); break ;\
case 1: (__ti)->body((__ti)->args[0].access.data); break ;\
case 2: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data); break ;\
case 3: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data); break ;\
case 4: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data); break ;\
case 5: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data); break ;\
case 6: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data, (__ti)->args[5].access.data); break ;\
case 7: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data, (__ti)->args[5].access.data, (__ti)->args[6].access.data); break ;\
case 8: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data, (__ti)->args[5].access.data, (__ti)->args[6].access.data, (__ti)->args[7].access.data); break ;\
case 9: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data, (__ti)->args[5].access.data, (__ti)->args[6].access.data, (__ti)->args[7].access.data, (__ti)->args[8].access.data); break ;\
case 10: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data, (__ti)->args[5].access.data, (__ti)->args[6].access.data, (__ti)->args[7].access.data, (__ti)->args[8].access.data, (__ti)->args[9].access.data); break ;\
case 11: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data, (__ti)->args[5].access.data, (__ti)->args[6].access.data, (__ti)->args[7].access.data, (__ti)->args[8].access.data, (__ti)->args[9].access.data, (__ti)->args[10].access.data); break ;\
case 12: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data, (__ti)->args[5].access.data, (__ti)->args[6].access.data, (__ti)->args[7].access.data, (__ti)->args[8].access.data, (__ti)->args[9].access.data, (__ti)->args[10].access.data, (__ti)->args[11].access.data); break ;\
case 13: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data, (__ti)->args[5].access.data, (__ti)->args[6].access.data, (__ti)->args[7].access.data, (__ti)->args[8].access.data, (__ti)->args[9].access.data, (__ti)->args[10].access.data, (__ti)->args[11].access.data, (__ti)->args[12].access.data); break ;\
case 14: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data, (__ti)->args[5].access.data, (__ti)->args[6].access.data, (__ti)->args[7].access.data, (__ti)->args[8].access.data, (__ti)->args[9].access.data, (__ti)->args[10].access.data, (__ti)->args[11].access.data, (__ti)->args[12].access.data, (__ti)->args[13].access.data); break ;\
case 15: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data, (__ti)->args[5].access.data, (__ti)->args[6].access.data, (__ti)->args[7].access.data, (__ti)->args[8].access.data, (__ti)->args[9].access.data, (__ti)->args[10].access.data, (__ti)->args[11].access.data, (__ti)->args[12].access.data, (__ti)->args[13].access.data, (__ti)->args[14].access.data); break ;\
case 16: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data, (__ti)->args[5].access.data, (__ti)->args[6].access.data, (__ti)->args[7].access.data, (__ti)->args[8].access.data, (__ti)->args[9].access.data, (__ti)->args[10].access.data, (__ti)->args[11].access.data, (__ti)->args[12].access.data, (__ti)->args[13].access.data, (__ti)->args[14].access.data, (__ti)->args[15].access.data); break ;\
case 17: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data, (__ti)->args[5].access.data, (__ti)->args[6].access.data, (__ti)->args[7].access.data, (__ti)->args[8].access.data, (__ti)->args[9].access.data, (__ti)->args[10].access.data, (__ti)->args[11].access.data, (__ti)->args[12].access.data, (__ti)->args[13].access.data, (__ti)->args[14].access.data, (__ti)->args[15].access.data, (__ti)->args[16].access.data); break ;\
case 18: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data, (__ti)->args[5].access.data, (__ti)->args[6].access.data, (__ti)->args[7].access.data, (__ti)->args[8].access.data, (__ti)->args[9].access.data, (__ti)->args[10].access.data, (__ti)->args[11].access.data, (__ti)->args[12].access.data, (__ti)->args[13].access.data, (__ti)->args[14].access.data, (__ti)->args[15].access.data, (__ti)->args[16].access.data, (__ti)->args[17].access.data); break ;\
case 19: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data, (__ti)->args[5].access.data, (__ti)->args[6].access.data, (__ti)->args[7].access.data, (__ti)->args[8].access.data, (__ti)->args[9].access.data, (__ti)->args[10].access.data, (__ti)->args[11].access.data, (__ti)->args[12].access.data, (__ti)->args[13].access.data, (__ti)->args[14].access.data, (__ti)->args[15].access.data, (__ti)->args[16].access.data, (__ti)->args[17].access.data, (__ti)->args[18].access.data); break ;\
case 20: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data, (__ti)->args[5].access.data, (__ti)->args[6].access.data, (__ti)->args[7].access.data, (__ti)->args[8].access.data, (__ti)->args[9].access.data, (__ti)->args[10].access.data, (__ti)->args[11].access.data, (__ti)->args[12].access.data, (__ti)->args[13].access.data, (__ti)->args[14].access.data, (__ti)->args[15].access.data, (__ti)->args[16].access.data, (__ti)->args[17].access.data, (__ti)->args[18].access.data, (__ti)->args[19].access.data); break ;\
case 21: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data, (__ti)->args[5].access.data, (__ti)->args[6].access.data, (__ti)->args[7].access.data, (__ti)->args[8].access.data, (__ti)->args[9].access.data, (__ti)->args[10].access.data, (__ti)->args[11].access.data, (__ti)->args[12].access.data, (__ti)->args[13].access.data, (__ti)->args[14].access.data, (__ti)->args[15].access.data, (__ti)->args[16].access.data, (__ti)->args[17].access.data, (__ti)->args[18].access.data, (__ti)->args[19].access.data, (__ti)->args[20].access.data); break ;\
case 22: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data, (__ti)->args[5].access.data, (__ti)->args[6].access.data, (__ti)->args[7].access.data, (__ti)->args[8].access.data, (__ti)->args[9].access.data, (__ti)->args[10].access.data, (__ti)->args[11].access.data, (__ti)->args[12].access.data, (__ti)->args[13].access.data, (__ti)->args[14].access.data, (__ti)->args[15].access.data, (__ti)->args[16].access.data, (__ti)->args[17].access.data, (__ti)->args[18].access.data, (__ti)->args[19].access.data, (__ti)->args[20].access.data, (__ti)->args[21].access.data); break ;\
case 23: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data, (__ti)->args[5].access.data, (__ti)->args[6].access.data, (__ti)->args[7].access.data, (__ti)->args[8].access.data, (__ti)->args[9].access.data, (__ti)->args[10].access.data, (__ti)->args[11].access.data, (__ti)->args[12].access.data, (__ti)->args[13].access.data, (__ti)->args[14].access.data, (__ti)->args[15].access.data, (__ti)->args[16].access.data, (__ti)->args[17].access.data, (__ti)->args[18].access.data, (__ti)->args[19].access.data, (__ti)->args[20].access.data, (__ti)->args[21].access.data, (__ti)->args[22].access.data); break ;\
case 24: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data, (__ti)->args[5].access.data, (__ti)->args[6].access.data, (__ti)->args[7].access.data, (__ti)->args[8].access.data, (__ti)->args[9].access.data, (__ti)->args[10].access.data, (__ti)->args[11].access.data, (__ti)->args[12].access.data, (__ti)->args[13].access.data, (__ti)->args[14].access.data, (__ti)->args[15].access.data, (__ti)->args[16].access.data, (__ti)->args[17].access.data, (__ti)->args[18].access.data, (__ti)->args[19].access.data, (__ti)->args[20].access.data, (__ti)->args[21].access.data, (__ti)->args[22].access.data, (__ti)->args[23].access.data); break ;\
case 25: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data, (__ti)->args[5].access.data, (__ti)->args[6].access.data, (__ti)->args[7].access.data, (__ti)->args[8].access.data, (__ti)->args[9].access.data, (__ti)->args[10].access.data, (__ti)->args[11].access.data, (__ti)->args[12].access.data, (__ti)->args[13].access.data, (__ti)->args[14].access.data, (__ti)->args[15].access.data, (__ti)->args[16].access.data, (__ti)->args[17].access.data, (__ti)->args[18].access.data, (__ti)->args[19].access.data, (__ti)->args[20].access.data, (__ti)->args[21].access.data, (__ti)->args[22].access.data, (__ti)->args[23].access.data, (__ti)->args[24].access.data); break ;\
case 26: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data, (__ti)->args[5].access.data, (__ti)->args[6].access.data, (__ti)->args[7].access.data, (__ti)->args[8].access.data, (__ti)->args[9].access.data, (__ti)->args[10].access.data, (__ti)->args[11].access.data, (__ti)->args[12].access.data, (__ti)->args[13].access.data, (__ti)->args[14].access.data, (__ti)->args[15].access.data, (__ti)->args[16].access.data, (__ti)->args[17].access.data, (__ti)->args[18].access.data, (__ti)->args[19].access.data, (__ti)->args[20].access.data, (__ti)->args[21].access.data, (__ti)->args[22].access.data, (__ti)->args[23].access.data, (__ti)->args[24].access.data, (__ti)->args[25].access.data); break ;\
case 27: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data, (__ti)->args[5].access.data, (__ti)->args[6].access.data, (__ti)->args[7].access.data, (__ti)->args[8].access.data, (__ti)->args[9].access.data, (__ti)->args[10].access.data, (__ti)->args[11].access.data, (__ti)->args[12].access.data, (__ti)->args[13].access.data, (__ti)->args[14].access.data, (__ti)->args[15].access.data, (__ti)->args[16].access.data, (__ti)->args[17].access.data, (__ti)->args[18].access.data, (__ti)->args[19].access.data, (__ti)->args[20].access.data, (__ti)->args[21].access.data, (__ti)->args[22].access.data, (__ti)->args[23].access.data, (__ti)->args[24].access.data, (__ti)->args[25].access.data, (__ti)->args[26].access.data); break ;\
case 28: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data, (__ti)->args[5].access.data, (__ti)->args[6].access.data, (__ti)->args[7].access.data, (__ti)->args[8].access.data, (__ti)->args[9].access.data, (__ti)->args[10].access.data, (__ti)->args[11].access.data, (__ti)->args[12].access.data, (__ti)->args[13].access.data, (__ti)->args[14].access.data, (__ti)->args[15].access.data, (__ti)->args[16].access.data, (__ti)->args[17].access.data, (__ti)->args[18].access.data, (__ti)->args[19].access.data, (__ti)->args[20].access.data, (__ti)->args[21].access.data, (__ti)->args[22].access.data, (__ti)->args[23].access.data, (__ti)->args[24].access.data, (__ti)->args[25].access.data, (__ti)->args[26].access.data, (__ti)->args[27].access.data); break ;\
case 29: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data, (__ti)->args[5].access.data, (__ti)->args[6].access.data, (__ti)->args[7].access.data, (__ti)->args[8].access.data, (__ti)->args[9].access.data, (__ti)->args[10].access.data, (__ti)->args[11].access.data, (__ti)->args[12].access.data, (__ti)->args[13].access.data, (__ti)->args[14].access.data, (__ti)->args[15].access.data, (__ti)->args[16].access.data, (__ti)->args[17].access.data, (__ti)->args[18].access.data, (__ti)->args[19].access.data, (__ti)->args[20].access.data, (__ti)->args[21].access.data, (__ti)->args[22].access.data, (__ti)->args[23].access.data, (__ti)->args[24].access.data, (__ti)->args[25].access.data, (__ti)->args[26].access.data, (__ti)->args[27].access.data, (__ti)->args[28].access.data); break ;\
case 30: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data, (__ti)->args[5].access.data, (__ti)->args[6].access.data, (__ti)->args[7].access.data, (__ti)->args[8].access.data, (__ti)->args[9].access.data, (__ti)->args[10].access.data, (__ti)->args[11].access.data, (__ti)->args[12].access.data, (__ti)->args[13].access.data, (__ti)->args[14].access.data, (__ti)->args[15].access.data, (__ti)->args[16].access.data, (__ti)->args[17].access.data, (__ti)->args[18].access.data, (__ti)->args[19].access.data, (__ti)->args[20].access.data, (__ti)->args[21].access.data, (__ti)->args[22].access.data, (__ti)->args[23].access.data, (__ti)->args[24].access.data, (__ti)->args[25].access.data, (__ti)->args[26].access.data, (__ti)->args[27].access.data, (__ti)->args[28].access.data, (__ti)->args[29].access.data); break ;\
case 31: (__ti)->body((__ti)->args[0].access.data, (__ti)->args[1].access.data, (__ti)->args[2].access.data, (__ti)->args[3].access.data, (__ti)->args[4].access.data, (__ti)->args[5].access.data, (__ti)->args[6].access.data, (__ti)->args[7].access.data, (__ti)->args[8].access.data, (__ti)->args[9].access.data, (__ti)->args[10].access.data, (__ti)->args[11].access.data, (__ti)->args[12].access.data, (__ti)->args[13].access.data, (__ti)->args[14].access.data, (__ti)->args[15].access.data, (__ti)->args[16].access.data, (__ti)->args[17].access.data, (__ti)->args[18].access.data, (__ti)->args[19].access.data, (__ti)->args[20].access.data, (__ti)->args[21].access.data, (__ti)->args[22].access.data, (__ti)->args[23].access.data, (__ti)->args[24].access.data, (__ti)->args[25].access.data, (__ti)->args[26].access.data, (__ti)->args[27].access.data, (__ti)->args[28].access.data, (__ti)->args[29].access.data, (__ti)->args[30].access.data); break ;\
default: kaapi_abort(); break ;\
}
#endif
