! kaapi error codes
      INTEGER(4), PARAMETER :: KAAPIF_SUCCESS=0
      INTEGER(4), PARAMETER :: KAAPIF_ERR_FAILURE=-1
      INTEGER(4), PARAMETER :: KAAPIF_ERR_EINVAL=-2
      INTEGER(4), PARAMETER :: KAAPIF_ERR_UNIMPL=-3

! kaapi data types
      INTEGER(4), PARAMETER :: KAAPIF_TYPE_CHAR=0
      INTEGER(4), PARAMETER :: KAAPIF_TYPE_INT=1
      INTEGER(4), PARAMETER :: KAAPIF_TYPE_REAL=2
      INTEGER(4), PARAMETER :: KAAPIF_TYPE_DOUBLE=3
      INTEGER(4), PARAMETER :: KAAPIF_TYPE_PTR=4

! kaapi modes
      INTEGER(4), PARAMETER :: KAAPIF_MODE_R=0
      INTEGER(4), PARAMETER :: KAAPIF_MODE_W=1
      INTEGER(4), PARAMETER :: KAAPIF_MODE_RW=2
      INTEGER(4), PARAMETER :: KAAPIF_MODE_V=3
