C kaapi error codes
	INTEGER*4 KAAPIF_SUCCESS
	INTEGER*4 KAAPIF_ERR_FAILURE
	INTEGER*4 KAAPIF_ERR_EINVAL
	INTEGER*4 KAAPIF_ERR_UNIMPL
	PARAMETER (KAAPIF_SUCCESS=0)
	PARAMETER (KAAPIF_ERR_FAILURE=-1)
	PARAMETER (KAAPIF_ERR_EINVAL=-2)
	PARAMETER (KAAPIF_ERR_UNIMPL=-3)

C kaapi data types
	INTEGER*4 KAAPIF_TYPE_CHAR
	INTEGER*4 KAAPIF_TYPE_INT
	INTEGER*4 KAAPIF_TYPE_REAL
	INTEGER*4 KAAPIF_TYPE_DOUBLE
	INTEGER*4 KAAPIF_TYPE_PTR
	PARAMETER (KAAPIF_TYPE_CHAR=0)
	PARAMETER (KAAPIF_TYPE_INT=1)
	PARAMETER (KAAPIF_TYPE_REAL=2)
	PARAMETER (KAAPIF_TYPE_DOUBLE=3)
	PARAMETER (KAAPIF_TYPE_PTR=4)

C kaapi modes
	INTEGER*4 KAAPIF_MODE_R
	INTEGER*4 KAAPIF_MODE_W
	INTEGER*4 KAAPIF_MODE_RW
	INTEGER*4 KAAPIF_MODE_V
	PARAMETER (KAAPIF_MODE_R=0)
	PARAMETER (KAAPIF_MODE_W=1)
	PARAMETER (KAAPIF_MODE_RW=2)
	PARAMETER (KAAPIF_MODE_V=3)
