#ifndef CONFIG_H_INCLUDED
# define CONFIG_H_INCLUDED


#define CONFIG_STRIDE_SIZE (1024)
#define CONFIG_ARRAY_SIZE (64 * 1024 * 1024)
/* #define CONFIG_ARRAY_SIZE (768 * 1024) */
#define CONFIG_DO_CHECK 1
#define CONFIG_DO_BENCH 1
#define CONFIG_USE_INPLACE_MERGE 0
#define CONFIG_USE_PARALLEL_MERGE 1
#define CONFIG_PARALLEL_MERGE_GRAIN 0x1000
#define CONFIG_LEAF_SIZE (0x1000 / 2)
#define CONFIG_USE_MEIN_MALLOC 1
#define CONFIG_USE_MEMCPY_FREE_TASK 1


#endif /* ! CONFIG_H_INCLUDED */
