\input texinfo
@c %** start of header
@setfilename kaapi.info
@settitle kaapi 
@include version.texi
@dircategory Software libraries
@direntry
* KAAPI: (kaapi).              Kernel for Adaptative, Asynchronous Parallel and Interactive programming
@end direntry
@c %** end of header

@copying
This manual is for X-Kaapi (version @value{VERSION}, @value{UPDATED}),
Hyantes is free software; you can redistribute it and/or modify
it under the terms of the CeCill-C License (GPL like license).

Copyright @copyright{} 2010 LIG/INRIA
@end copying

@titlepage
@title KAAPI 
@subtitle for version @value{VERSION}, @value{UPDATED}
@author Kaapi Team (@email{kaapi-leaders@@lists.gforge.inria.fr})
@page
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top Kaapi
This manual is for X-Kaapi library (version @value{VERSION}, @value{UPDATED}).
@end ifnottex

@menu
* kaapi overview:: Overview of the package
* install guide:: Installation guide
* compile and run:: Link program with @code{KAAPI} 
* API-Kaapi :: Detailed overview of the C++ API
* API-Athapascan :: Overview of old Athapascan API
* tutorials:: understand the basics
* Doxygen :: functions and classes exported by the Kaapi library
* function methods and classes index :: quickly find your way in the api
@end menu
@c * contacts :: flame or grats the authors


@node kaapi overview
@chapter Overview
X-Kaapi is a runtime high performance parallelism targeting multicore and distributed architectures. It relies on workstealing paradigms. The core library comes with a full set of complementary programming interfaces, allowing for different abstraction levels. The following documents the install process, runtime options, as well as a description of APIs lying on top of the runtime and a set of examples.

Main features are

@itemize
@item It is based on work-stealing algorithms ;
@item It can run on various processors ;
@item It can run on various architectures (clusters or grids) ;
@item It contains non-blocking and scalable algorithms ;
@end itemize


@c -------------------------------------------
@include install/install.texi
@include install/compile_and_run.texi
@include kaapi/overview.texi
@include kaapi/api.texi
@include athapascan/overview.texi
@include tutorial/tutorial.texi
@include athapascan/api.texi
@c -------------------------------------------

@node function methods and classes index
@unnumbered Function, methods and classes index
@printindex fn

@bye

